### ISSUE TITLE
Usage with Signoz

### ISSUE THREAD

**Issue by Mohit21GoJs** [lmnr-ai/lmnr#28]
Hi Team, we are using Signoz for our monitoring, is there a way we can connect Signoz with Lmnr, i would like to use their self hosted version to ingest my Lmnr logs into it: https://signoz.io/docs/introduction/

Similar to https://www.traceloop.com/docs/openllmetry/integrations/signoz#with-self-hosted-version

Is it possible?

**Comment by dinmukhamedm** [comment]
Hi Mohit, thanks for your question. If you are not going to use the Laminar dashboard, analytics, and frontend, and just want to use Laminar for instrumentation and sending your logs to Signoz, I'd recommend going with Traceloop/OpenLLMetry. 

Our trace exporters are very much based on OpenLLMetry, so if you use Traceloop instead, you will not see major differences. Migration shouldn't bee too complex either.

We can easily add a few configs like the ones you linked so that you use custom exporters, but I don't know if that makes sense to do. Let us know if you see reasons to use Laminar over pure OpenLLMetry to just send the logs.

**Comment by dinmukhamedm** [comment]
Continued in #179
